sudo: required

dist: bionic

language: python

python:
    - 2.7
    - 3.6
    - 3.8
    ## PyPy versions
    #- pypy2.7-6.0
    #- pypy3

jobs:
  include:
    - os: osx
      osx_image: xcode12
      language: sh
      env:
        - HOMEBREW_NO_INSTALL_CLEANUP=1
        - HOMEBREW_NO_ANALYTICS=1
  allow_failures:
    - python: 2.7
    #- python: pypy2.7-6.0

addons:
    apt:
        update: true
        packages:
            - build-essential
            - ca-certificates
            - curl
            - git
            - pkg-config
            - gzip
            - software-properties-common
            - python-dev
            - python3-dev
            - libgdbm-dev
            - libfftw3-dev
            - libcfitsio-dev
            - libboost-python-dev
    homebrew:
        update: false
        packages:
            - python3
            - pkg-config
            - git
            - fftw

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:kernsuite/kern-4; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -q update; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install casacore-dev wcslib-dev; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then python3 -m pip install --upgrade virtualenv; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then virtualenv -p python3 "$HOME/venv"; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then source "$HOME/venv/bin/activate"; fi

install:
    - pip install \
        setuptools \
        numpy \
        matplotlib \
        scipy \
        pyephem==3.7.6.0 \
        jupyterlab \
        jupyter_client \
        nbformat \
        nbconvert \
        coveralls \
        codecov
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install python-casacore; fi
    - if [ "`python -V | grep -v '2.7.'`" = "" ]; then pip install "healpy<1.14.0"; fi
    - pip install aipy
    - pip install .
    - curl https://fornax.phys.unm.edu/lwa/data/igsg0970.18i.gz -o $HOME/.lsl/ionospheric_cache/igsg0970.18i.gz --create-dirs
    - curl https://fornax.phys.unm.edu/lwa/data/jplg0970.18i.gz -o $HOME/.lsl/ionospheric_cache/jplg0970.18i.gz --create-dirs
    - curl https://fornax.phys.unm.edu/lwa/data/codg0970.18i.gz -o $HOME/.lsl/ionospheric_cache/codg0970.18i.gz --create-dirs
    - curl https://fornax.phys.unm.edu/lwa/data/uqrg0970.18i.gz -o $HOME/.lsl/ionospheric_cache/uqrg0970.18i.gz --create-dirs

script:
    - cd tests


script:
    - cd tests
    - coverage run --source=lsl -m unittest discover

after_success:
    - cd tests
    - coveralls
    - codecov

cache:
  directories:
    - $HOME/.astropy/cache
    - $HOME/.lsl/ionospheric_cache
