sudo: required
  
language: python

python:
    - 2.7
    - 3.6
    ## PyPy versions
    #- pypy2.7-6.0
    #- pypy3


addons:
    apt:
        packages:
            - build-essential
            - curl
            - git
            - pkg-config
            - software-properties-common
            - python-dev
            - python3-dev
            - libfftw3-dev
            - libcfitsio-dev
            - libboost-python-dev

before_install:
    - sudo add-apt-repository -y ppa:kernsuite/kern-3
    - sudo apt-get -q update
    - sudo apt-get -y install casacore-dev wcslib-dev
install:
    - pip install \
        setuptools \
        numpy \
        matplotlib \
        scipy \
        pyephem==3.7.6.0 \
        python-casacore \
        coveralls \
        codecov
    - pip install astropy==3.2.3
    - pip install aipy
    - pip install .
    - python -c "from astropy.utils.data import download_file; download_file('https://datacenter.iers.org/data/9/finals2000A.all', cache=True)"


script:
    - cd tests
    - coverage run --source=lsl -m unittest discover

after_success:
    - cd tests
    - coveralls
    - codecov

cache:
  directories:
    - $HOME/.astropy/cache
