name: LSL
on: [push, pull_request]
jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['2.7', '3.6', '3.8']
    steps:
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install -y build-essential ca-certificates curl git pkg-config gzip libgddm-dev libfftw3-dev libcfitsio-dev
      - if: ${{ matrix.os == 'macos-latest' }}
        run: sudo homebrew install pkg-config fftw
        
  build:
    runs-on: [ubuntu-latest, macos-latest]
    needs: setup
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - run: pip install setuptools numpy matplotlib scipy pyephem==3.7.6.0 jupyterlab jupyter_client nbformat nbconvert coveralls codecov
      - run: pip install aipy
      - run: pip install .
  test:
    runs-on: [ubuntu-latest, macos-latest]
    needs: [setup, build]
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: cd tests && coverage run --source=lsl -m unittest discover
    
